apiVersion: apps/v1 
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 1
  template:
    spec:
      containers:
      - name: hello-world
        resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits: 
              cpu: 50m
              memory: 50Mi




