apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-production
resources:
  - ../../base

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: hello-world
    path: patch.yaml
